# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/neptoon/Desktop/VIA-SEES/SimpleDet2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/neptoon/Desktop/VIA-SEES/SimpleDet2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/neptoon/Desktop/VIA-SEES/SimpleDet2/CMakeFiles /Users/neptoon/Desktop/VIA-SEES/SimpleDet2//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/neptoon/Desktop/VIA-SEES/SimpleDet2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SimpleDet2

# Build rule for target.
SimpleDet2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SimpleDet2
.PHONY : SimpleDet2

# fast build rule for target.
SimpleDet2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/build
.PHONY : SimpleDet2/fast

#=============================================================================
# Target rules for targets named AS

# Build rule for target.
AS: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AS
.PHONY : AS

# fast build rule for target.
AS/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AS.dir/build.make CMakeFiles/AS.dir/build
.PHONY : AS/fast

SimpleDet.o: SimpleDet.cc.o
.PHONY : SimpleDet.o

# target to build an object file
SimpleDet.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/SimpleDet.cc.o
.PHONY : SimpleDet.cc.o

SimpleDet.i: SimpleDet.cc.i
.PHONY : SimpleDet.i

# target to preprocess a source file
SimpleDet.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/SimpleDet.cc.i
.PHONY : SimpleDet.cc.i

SimpleDet.s: SimpleDet.cc.s
.PHONY : SimpleDet.s

# target to generate assembly for a file
SimpleDet.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/SimpleDet.cc.s
.PHONY : SimpleDet.cc.s

src/SimpleDetActionInitialization.o: src/SimpleDetActionInitialization.cc.o
.PHONY : src/SimpleDetActionInitialization.o

# target to build an object file
src/SimpleDetActionInitialization.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetActionInitialization.cc.o
.PHONY : src/SimpleDetActionInitialization.cc.o

src/SimpleDetActionInitialization.i: src/SimpleDetActionInitialization.cc.i
.PHONY : src/SimpleDetActionInitialization.i

# target to preprocess a source file
src/SimpleDetActionInitialization.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetActionInitialization.cc.i
.PHONY : src/SimpleDetActionInitialization.cc.i

src/SimpleDetActionInitialization.s: src/SimpleDetActionInitialization.cc.s
.PHONY : src/SimpleDetActionInitialization.s

# target to generate assembly for a file
src/SimpleDetActionInitialization.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetActionInitialization.cc.s
.PHONY : src/SimpleDetActionInitialization.cc.s

src/SimpleDetDetectorConstruction.o: src/SimpleDetDetectorConstruction.cc.o
.PHONY : src/SimpleDetDetectorConstruction.o

# target to build an object file
src/SimpleDetDetectorConstruction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetDetectorConstruction.cc.o
.PHONY : src/SimpleDetDetectorConstruction.cc.o

src/SimpleDetDetectorConstruction.i: src/SimpleDetDetectorConstruction.cc.i
.PHONY : src/SimpleDetDetectorConstruction.i

# target to preprocess a source file
src/SimpleDetDetectorConstruction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetDetectorConstruction.cc.i
.PHONY : src/SimpleDetDetectorConstruction.cc.i

src/SimpleDetDetectorConstruction.s: src/SimpleDetDetectorConstruction.cc.s
.PHONY : src/SimpleDetDetectorConstruction.s

# target to generate assembly for a file
src/SimpleDetDetectorConstruction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetDetectorConstruction.cc.s
.PHONY : src/SimpleDetDetectorConstruction.cc.s

src/SimpleDetDetectorMessenger.o: src/SimpleDetDetectorMessenger.cc.o
.PHONY : src/SimpleDetDetectorMessenger.o

# target to build an object file
src/SimpleDetDetectorMessenger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetDetectorMessenger.cc.o
.PHONY : src/SimpleDetDetectorMessenger.cc.o

src/SimpleDetDetectorMessenger.i: src/SimpleDetDetectorMessenger.cc.i
.PHONY : src/SimpleDetDetectorMessenger.i

# target to preprocess a source file
src/SimpleDetDetectorMessenger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetDetectorMessenger.cc.i
.PHONY : src/SimpleDetDetectorMessenger.cc.i

src/SimpleDetDetectorMessenger.s: src/SimpleDetDetectorMessenger.cc.s
.PHONY : src/SimpleDetDetectorMessenger.s

# target to generate assembly for a file
src/SimpleDetDetectorMessenger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetDetectorMessenger.cc.s
.PHONY : src/SimpleDetDetectorMessenger.cc.s

src/SimpleDetEventAction.o: src/SimpleDetEventAction.cc.o
.PHONY : src/SimpleDetEventAction.o

# target to build an object file
src/SimpleDetEventAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetEventAction.cc.o
.PHONY : src/SimpleDetEventAction.cc.o

src/SimpleDetEventAction.i: src/SimpleDetEventAction.cc.i
.PHONY : src/SimpleDetEventAction.i

# target to preprocess a source file
src/SimpleDetEventAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetEventAction.cc.i
.PHONY : src/SimpleDetEventAction.cc.i

src/SimpleDetEventAction.s: src/SimpleDetEventAction.cc.s
.PHONY : src/SimpleDetEventAction.s

# target to generate assembly for a file
src/SimpleDetEventAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetEventAction.cc.s
.PHONY : src/SimpleDetEventAction.cc.s

src/SimpleDetHit.o: src/SimpleDetHit.cc.o
.PHONY : src/SimpleDetHit.o

# target to build an object file
src/SimpleDetHit.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetHit.cc.o
.PHONY : src/SimpleDetHit.cc.o

src/SimpleDetHit.i: src/SimpleDetHit.cc.i
.PHONY : src/SimpleDetHit.i

# target to preprocess a source file
src/SimpleDetHit.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetHit.cc.i
.PHONY : src/SimpleDetHit.cc.i

src/SimpleDetHit.s: src/SimpleDetHit.cc.s
.PHONY : src/SimpleDetHit.s

# target to generate assembly for a file
src/SimpleDetHit.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetHit.cc.s
.PHONY : src/SimpleDetHit.cc.s

src/SimpleDetMagneticField.o: src/SimpleDetMagneticField.cc.o
.PHONY : src/SimpleDetMagneticField.o

# target to build an object file
src/SimpleDetMagneticField.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetMagneticField.cc.o
.PHONY : src/SimpleDetMagneticField.cc.o

src/SimpleDetMagneticField.i: src/SimpleDetMagneticField.cc.i
.PHONY : src/SimpleDetMagneticField.i

# target to preprocess a source file
src/SimpleDetMagneticField.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetMagneticField.cc.i
.PHONY : src/SimpleDetMagneticField.cc.i

src/SimpleDetMagneticField.s: src/SimpleDetMagneticField.cc.s
.PHONY : src/SimpleDetMagneticField.s

# target to generate assembly for a file
src/SimpleDetMagneticField.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetMagneticField.cc.s
.PHONY : src/SimpleDetMagneticField.cc.s

src/SimpleDetPhysicsList.o: src/SimpleDetPhysicsList.cc.o
.PHONY : src/SimpleDetPhysicsList.o

# target to build an object file
src/SimpleDetPhysicsList.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetPhysicsList.cc.o
.PHONY : src/SimpleDetPhysicsList.cc.o

src/SimpleDetPhysicsList.i: src/SimpleDetPhysicsList.cc.i
.PHONY : src/SimpleDetPhysicsList.i

# target to preprocess a source file
src/SimpleDetPhysicsList.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetPhysicsList.cc.i
.PHONY : src/SimpleDetPhysicsList.cc.i

src/SimpleDetPhysicsList.s: src/SimpleDetPhysicsList.cc.s
.PHONY : src/SimpleDetPhysicsList.s

# target to generate assembly for a file
src/SimpleDetPhysicsList.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetPhysicsList.cc.s
.PHONY : src/SimpleDetPhysicsList.cc.s

src/SimpleDetPrimaryGeneratorAction.o: src/SimpleDetPrimaryGeneratorAction.cc.o
.PHONY : src/SimpleDetPrimaryGeneratorAction.o

# target to build an object file
src/SimpleDetPrimaryGeneratorAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetPrimaryGeneratorAction.cc.o
.PHONY : src/SimpleDetPrimaryGeneratorAction.cc.o

src/SimpleDetPrimaryGeneratorAction.i: src/SimpleDetPrimaryGeneratorAction.cc.i
.PHONY : src/SimpleDetPrimaryGeneratorAction.i

# target to preprocess a source file
src/SimpleDetPrimaryGeneratorAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetPrimaryGeneratorAction.cc.i
.PHONY : src/SimpleDetPrimaryGeneratorAction.cc.i

src/SimpleDetPrimaryGeneratorAction.s: src/SimpleDetPrimaryGeneratorAction.cc.s
.PHONY : src/SimpleDetPrimaryGeneratorAction.s

# target to generate assembly for a file
src/SimpleDetPrimaryGeneratorAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetPrimaryGeneratorAction.cc.s
.PHONY : src/SimpleDetPrimaryGeneratorAction.cc.s

src/SimpleDetRunAction.o: src/SimpleDetRunAction.cc.o
.PHONY : src/SimpleDetRunAction.o

# target to build an object file
src/SimpleDetRunAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetRunAction.cc.o
.PHONY : src/SimpleDetRunAction.cc.o

src/SimpleDetRunAction.i: src/SimpleDetRunAction.cc.i
.PHONY : src/SimpleDetRunAction.i

# target to preprocess a source file
src/SimpleDetRunAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetRunAction.cc.i
.PHONY : src/SimpleDetRunAction.cc.i

src/SimpleDetRunAction.s: src/SimpleDetRunAction.cc.s
.PHONY : src/SimpleDetRunAction.s

# target to generate assembly for a file
src/SimpleDetRunAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetRunAction.cc.s
.PHONY : src/SimpleDetRunAction.cc.s

src/SimpleDetSD.o: src/SimpleDetSD.cc.o
.PHONY : src/SimpleDetSD.o

# target to build an object file
src/SimpleDetSD.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetSD.cc.o
.PHONY : src/SimpleDetSD.cc.o

src/SimpleDetSD.i: src/SimpleDetSD.cc.i
.PHONY : src/SimpleDetSD.i

# target to preprocess a source file
src/SimpleDetSD.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetSD.cc.i
.PHONY : src/SimpleDetSD.cc.i

src/SimpleDetSD.s: src/SimpleDetSD.cc.s
.PHONY : src/SimpleDetSD.s

# target to generate assembly for a file
src/SimpleDetSD.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetSD.cc.s
.PHONY : src/SimpleDetSD.cc.s

src/SimpleDetSteppingAction.o: src/SimpleDetSteppingAction.cc.o
.PHONY : src/SimpleDetSteppingAction.o

# target to build an object file
src/SimpleDetSteppingAction.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetSteppingAction.cc.o
.PHONY : src/SimpleDetSteppingAction.cc.o

src/SimpleDetSteppingAction.i: src/SimpleDetSteppingAction.cc.i
.PHONY : src/SimpleDetSteppingAction.i

# target to preprocess a source file
src/SimpleDetSteppingAction.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetSteppingAction.cc.i
.PHONY : src/SimpleDetSteppingAction.cc.i

src/SimpleDetSteppingAction.s: src/SimpleDetSteppingAction.cc.s
.PHONY : src/SimpleDetSteppingAction.s

# target to generate assembly for a file
src/SimpleDetSteppingAction.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetSteppingAction.cc.s
.PHONY : src/SimpleDetSteppingAction.cc.s

src/SimpleDetSteppingVerbose.o: src/SimpleDetSteppingVerbose.cc.o
.PHONY : src/SimpleDetSteppingVerbose.o

# target to build an object file
src/SimpleDetSteppingVerbose.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetSteppingVerbose.cc.o
.PHONY : src/SimpleDetSteppingVerbose.cc.o

src/SimpleDetSteppingVerbose.i: src/SimpleDetSteppingVerbose.cc.i
.PHONY : src/SimpleDetSteppingVerbose.i

# target to preprocess a source file
src/SimpleDetSteppingVerbose.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetSteppingVerbose.cc.i
.PHONY : src/SimpleDetSteppingVerbose.cc.i

src/SimpleDetSteppingVerbose.s: src/SimpleDetSteppingVerbose.cc.s
.PHONY : src/SimpleDetSteppingVerbose.s

# target to generate assembly for a file
src/SimpleDetSteppingVerbose.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SimpleDet2.dir/build.make CMakeFiles/SimpleDet2.dir/src/SimpleDetSteppingVerbose.cc.s
.PHONY : src/SimpleDetSteppingVerbose.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... AS"
	@echo "... SimpleDet2"
	@echo "... SimpleDet.o"
	@echo "... SimpleDet.i"
	@echo "... SimpleDet.s"
	@echo "... src/SimpleDetActionInitialization.o"
	@echo "... src/SimpleDetActionInitialization.i"
	@echo "... src/SimpleDetActionInitialization.s"
	@echo "... src/SimpleDetDetectorConstruction.o"
	@echo "... src/SimpleDetDetectorConstruction.i"
	@echo "... src/SimpleDetDetectorConstruction.s"
	@echo "... src/SimpleDetDetectorMessenger.o"
	@echo "... src/SimpleDetDetectorMessenger.i"
	@echo "... src/SimpleDetDetectorMessenger.s"
	@echo "... src/SimpleDetEventAction.o"
	@echo "... src/SimpleDetEventAction.i"
	@echo "... src/SimpleDetEventAction.s"
	@echo "... src/SimpleDetHit.o"
	@echo "... src/SimpleDetHit.i"
	@echo "... src/SimpleDetHit.s"
	@echo "... src/SimpleDetMagneticField.o"
	@echo "... src/SimpleDetMagneticField.i"
	@echo "... src/SimpleDetMagneticField.s"
	@echo "... src/SimpleDetPhysicsList.o"
	@echo "... src/SimpleDetPhysicsList.i"
	@echo "... src/SimpleDetPhysicsList.s"
	@echo "... src/SimpleDetPrimaryGeneratorAction.o"
	@echo "... src/SimpleDetPrimaryGeneratorAction.i"
	@echo "... src/SimpleDetPrimaryGeneratorAction.s"
	@echo "... src/SimpleDetRunAction.o"
	@echo "... src/SimpleDetRunAction.i"
	@echo "... src/SimpleDetRunAction.s"
	@echo "... src/SimpleDetSD.o"
	@echo "... src/SimpleDetSD.i"
	@echo "... src/SimpleDetSD.s"
	@echo "... src/SimpleDetSteppingAction.o"
	@echo "... src/SimpleDetSteppingAction.i"
	@echo "... src/SimpleDetSteppingAction.s"
	@echo "... src/SimpleDetSteppingVerbose.o"
	@echo "... src/SimpleDetSteppingVerbose.i"
	@echo "... src/SimpleDetSteppingVerbose.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

